name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
        - os: windows-latest
          runtime: win-x64
          version: 7.0.x
        - os: ubuntu-latest
          runtime: linux-x64
          version: 6.0

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        cd MemorySnapshotAnalyzer
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../Release -r ${{ matrix.runtime }} --self-contained true /p:UseAppHost=true

    - name: Execute unit tests
      run: dotnet test --no-restore
